import { Pet } from '@/types/types';

export const PETS_EN: Pet[] = [
  {
    id: 1,
    name: 'Taya',
    gender: 'Female',
    photo: 'https://egida.by/_dr/83/19542864.webp',
    type: 'puppy',
    breed: 'Mixed',
    age: '1 year',
    color: 'White, Brown, Black',
    character: 'Kind, playful',
    toilet: 'Trained for twice-a-day walks',
    medicalNeeds:
      'Fully treated against skin parasites. Spayed. Vaccinated on 04.09.2024 and 01.10.2024 (Multican-8).',
    feeding: 'Not picky about food',
    foundAt: '2023-07-02',
    history:
      'Taya was born where she was not expected, in a place where only the strongest survive. Thanks to kind people, she grew up and became a beauty. Taya knows what it means to be unwanted — she is happy to receive affection and kind words. She is ready to follow commands, just needs a bit of teaching. She is one of those dogs who would follow her owner to the ends of the earth. Young, playful, energetic, people-oriented, great with children and other animals. She is beautiful, graceful, and has a kind personality. All that’s left is to find her a loving family! If Taya has caught your heart, come meet her — she’s waiting for you!',
    shelter: 'Foster home',
    linkToPlatform: 'https://egida.by/catalog/8399',
    contactPhone: '+375 (29) 692-85-50, Tatyana',
  },
  {
    id: 2,
    name: 'Thomas',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/73161732.webp',
    type: 'kitten',
    breed: 'Mixed',
    age: '3 months',
    color: 'Black, Semi-fluffy',
    character: 'Cheerful, curious',
    toilet: 'Litter box trained',
    medicalNeeds:
      'Fully treated against skin parasites. Vaccinated on 20.09.2025 (Multifel + Rabifel).',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-09-25',
    history:
      'Affectionate, gentle, and sociable kitten Thomas is looking for a family. The baby is healthy, dewormed, and has had his first vaccination. He uses the litter box perfectly and eats both dry and wet food. He will make a wonderful home companion!',
    shelter: 'Foster home',
    linkToPlatform: 'https://egida.by/catalog/8400',
    contactPhone: '+375 (29) 692-85-50, Tatyana',
  },
  {
    id: 3,
    name: 'Leo',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/33494530.webp',
    type: 'kitten',
    breed: 'Mixed',
    age: '3 months',
    color: 'Black and white',
    character: 'Cheerful, curious',
    toilet: 'Litter box',
    medicalNeeds: 'Fully treated against skin parasites',
    feeding: 'High-quality mixed food',
    foundAt: '2025-10-11',
    history:
      'Cheerful and curious kitten Leo is looking for a home and loving owners. The boy is 3 months old, already litter-trained, has a good appetite, and gets along perfectly with other pets. With strangers he is a bit cautious at first, but once he gets used to them — he becomes the best friend of the whole family! Leo is still a child, so any object he finds can turn into a toy, and you’ll soon see funny pranks, acrobatic tricks, and “cat judo” — it’s a joy to watch! With this kitten, you’ll never be bored. Do you like him? Then call and come meet him — in person he will charm you even more!',
    shelter: 'Foster home',
    linkToPlatform: 'https://egida.by/catalog/50-1-0-8424',
    contactPhone: '+375 (29) 572-86-15, Olga',
  },
  {
    id: 4,
    name: 'Daisy',
    gender: 'Female',
    photo: 'https://egida.by/_dr/84/96831451.webp',
    type: 'cat',
    breed: 'Mixed',
    age: '5 months',
    color: 'Gray, tricolor',
    character: 'Playful, curious, affectionate, shy with strangers',
    toilet: 'Litter-trained with filler',
    medicalNeeds: 'Spayed, fully treated against skin parasites',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2023-09-24',
    history:
      'Cheerful, active, and affectionate Daisy is looking for her family. She is healthy, vaccinated, and litter-trained. In food she prefers preserves but also eats dry food well. Her coat is very beautiful — light gray tabby with red spots. She is a bit shy with strangers, so she will need a short adaptation period in her new home.',
    shelter: 'NGO “Egida”',
    linkToPlatform: 'https://egida.by/catalog/50-1-0-8416',
    contactPhone: '+375 (44) 768-26-13, Olga',
  },
  {
    id: 5,
    name: 'Sunny',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/78394289.webp',
    type: 'puppy',
    breed: 'Mixed',
    age: '6 months',
    color: 'Ginger',
    character: 'Playful, a bit cautious',
    toilet: 'In the process of being trained',
    medicalNeeds: 'Fully treated against skin parasites',
    feeding: 'Not picky about food',
    foundAt: '2023-09-17',
    history:
      'Soft-coated little modest Sunny! See for yourself — this short-legged boy will quietly walk right into your heart! He’s about 5.5 months old, shy, cat-friendly, and loves to run around. He plays joyfully with his sisters Peppy and Klepa, munches on both dry and wet food, and is waiting for YOU to visit!',
    shelter: 'Foster home',
    linkToPlatform: 'https://egida.by/catalog/20-1-0-8414',
    contactPhone: '+375 (29) 359-84-86, Galina',
  },
  {
    id: 6,
    name: 'Simon',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/11949883.webp',
    type: 'cat',
    breed: 'Mixed breed',
    age: '1.5 years',
    color: 'Gray',
    character: 'Affectionate, calm, sociable',
    toilet: 'Litter trained with filler',
    medicalNeeds: 'Neutered, fully treated for skin parasites',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2023-09-29',
    history:
      'Simon is a large young cat, about 1.5–2 years old. Calm, balanced, and affectionate. Gets along well with other cats. Litter box and scratching post trained. Healthy and neutered.',
    shelter: 'OOZJ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/30-1-0-8422',
    contactPhone: '+375 (44) 768-26-13, Olga',
  },
  {
    id: 7,
    name: 'Rosa',
    gender: 'Female',
    photo: 'https://egida.by/_dr/84/37863150.webp',
    type: 'kitten',
    breed: 'Mixed breed',
    age: '5 months',
    color: 'Gray, tricolor',
    character: 'Playful, affectionate, curious',
    toilet: 'Litter trained with filler',
    medicalNeeds:
      'Fully treated for skin parasites. Vaccinated on 20.09.2025 – Multifell + Rabifell',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-09-24',
    history:
      'Meet Rosa — a tame, affectionate, and sociable little kitty. She is 5 months old, healthy, vaccinated, and litter trained. She will become a wonderful friend and companion for a responsible adult. Adoption by agreement.',
    shelter: 'OOZJ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/50-1-0-8415',
    contactPhone: '+375 (44) 768-26-13, Olga',
  },
  {
    id: 8,
    name: 'Freddy',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/21680193.webp',
    type: 'puppy',
    breed: 'Mixed breed',
    age: '6 months',
    color: 'Ginger',
    character: 'Playful, a bit cautious',
    toilet: 'In the process of being trained',
    medicalNeeds:
      'Fully treated for skin parasites. Height at the withers: 25 cm',
    feeding: 'Not picky about food',
    foundAt: '2023-09-17',
    history:
      'Soft-haired little modest Freddy! See for yourself — short-legged, gentle, and sweet-natured. He’s already around 5.5 months old. Shy, cat-friendly little boy who plays with his sisters Peppi and Klepa, eats dry and wet food, and is waiting for YOU to visit!',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/20-1-0-8413',
    contactPhone: '+375 (29) 359-84-86, Galina',
  },
  {
    id: 9,
    name: 'Montana',
    gender: 'Female',
    photo: 'https://egida.by/_dr/83/50652867.webp',
    type: 'dog',
    breed: 'Mixed breed',
    age: '4 years',
    color: 'Brown',
    character: 'Very kind, responsive, obedient',
    toilet: 'Used to walking twice a day',
    medicalNeeds:
      'Fully treated for skin parasites. Vaccinated on 18.09.2024 – Nobivac DHPPi. Spayed. Height at the withers: 45 cm',
    feeding: 'Mixed feeding',
    foundAt: '2023-06-04',
    history:
      'If kindness had a name, it would be Montana. Very kind, forgiving, and gentle. Still young but already experienced life on the streets, Montana still sees only the good in everyone. Her pure soul is disarming — a wonderful girl with chocolate eyes. You can make her happy by giving her a place in your family! Call us — we’ll be glad to introduce you to our beautiful Montana!',
    shelter: 'Home of Saved Souls (HSS)',
    linkToPlatform: 'https://egida.by/catalog/8396',
    contactPhone: '+375 (29) 155-13-70, Dasha',
  },
  {
    id: 10,
    name: 'Lucky',
    gender: 'Female',
    photo: 'https://egida.by/_dr/77/67985524.jpg',
    type: 'dog',
    breed: 'American Pit Bull Terrier',
    age: '8 years',
    color: 'Ginger, short-haired, 45 cm at the withers',
    character: 'Active, obedient, people-oriented',
    toilet: 'Used to walking twice a day',
    medicalNeeds: 'Spayed, fully treated for skin parasites',
    feeding: 'Dry food',
    foundAt: '2024-11-01',
    history:
      'Intelligence and endurance, strength and grace — all these qualities came together in one wonderful dog. Lucky came to volunteers a little over a year ago after she was found wandering alone along a highway and brought to Minsk. A vet examination showed that she is about 8 years old and completely healthy. We don’t know where she lived before or why she ended up on the street, but during her time in foster care, we can confidently say Lucky is perfectly suited for apartment living: she waits for her two daily walks, doesn’t chew or damage anything, doesn’t jump on the bed, stays home alone calmly, and causes no problems for neighbors. Very human-oriented, loves attention and affection. Active. Spayed. Unfortunately, despite her love for people, she doesn’t get along with other animals. We are looking for a family without other pets or children under 12, either in an apartment or a private home, for responsible, mature people with stable means. You must be ready to work with a dog trainer, provide regular physical exercise (at least aerobic), buy quality food, and provide proper veterinary care when needed. The dog is adopted only under a formal transfer act with mutual legal obligations and rights. If you are confident in your abilities and nothing deters you, look at this wonderful dog — she will become a loyal and devoted friend!',
    shelter: 'OOZJ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/7749',
    contactPhone: '+375 (29) 275-50-03, Veronika',
  },
  {
    id: 11,
    name: 'Ray',
    gender: 'Male',
    photo: 'https://egida.by/_dr/83/11970694.webp',
    type: 'dog',
    breed: 'Chihuahua',
    age: '7 years',
    color: 'White, ginger, short-haired, 20 cm at the withers',
    character: 'Sociable, friendly, playful',
    toilet: 'Used to walking outdoors',
    medicalNeeds:
      'Neutered, fully treated for skin parasites. Vaccinated on 03.01.2025 – Nobivac Rabies',
    feeding: 'Dry food for small dogs',
    foundAt: '2025-03-31',
    history:
      'A charming gentleman in his prime. His former owners took him to be euthanized because they had no one to leave him with during their vacation. A wonderful little guy — affectionate, friendly, and gets along with everyone. 7 years old, neutered, used to walking three times a day. Looking for a home in Minsk with responsible adults without small children. Adoption by agreement.',
    shelter: 'OOZJ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/8359',
    contactPhone: '+375 (25) 785-07-23, Anastasia',
  },
  {
    id: 12,
    name: 'Umka',
    gender: 'Male',
    photo: 'https://egida.by/_dr/81/17909888.jpg',
    type: 'dog',
    breed: 'Mixed breed',
    age: '2 years',
    color: 'Ginger, short-haired, 50 cm at the withers',
    character: 'Calm, moderately active, kind',
    toilet: 'Used to walking twice a day',
    medicalNeeds: 'Fully treated for skin parasites',
    feeding: 'Eats dry food but prefers natural meals',
    foundAt: '2024-02-28',
    history:
      'Umka is a dog for the soul. About 2 years old — very beautiful and kind. Rescued from a village where he lived without shelter and often went hungry. Now he is in foster care, looking for his beloved owner. Preparing for vaccination, treated for parasites. Calm with other animals, good on the leash, house-trained. Adoption by agreement with feedback conditions for people who truly love and care for animals.',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/8196',
    contactPhone: '+375 (33) 313-99-87, Diana',
  },
  {
    id: 13,
    name: 'Eva',
    gender: 'Female',
    photo: 'https://egida.by/_dr/81/21276080.jpg',
    type: 'dog',
    breed: 'Russian Pie Dog (Hound)',
    age: '10 years',
    color: 'Tricolor, short-haired, 50 cm at the withers',
    character:
      'Sleeps a lot and contemplates life with a very noble expression',
    toilet: 'Used to walking three times a day',
    medicalNeeds: 'Fully treated for skin parasites. Has a mammary gland tumor',
    feeding: 'Dry food Monge VetSolution Dog Joint Mobility',
    foundAt: '2024-07-24',
    history:
      'To survive against all odds — that’s our Eva’s story. Betrayed by her owner, suffering severe injuries, and ignored by passersby, she still made it! Now she’s living her best life, lacking only that one special Human who will welcome her not just into their home but into their heart. Eva is an elderly dog, about 10+, sleeps a lot, and spends her time in quiet reflection with a noble face. Walks only to go potty. No one knows how much time she has left, but one thing is certain — this wonderful dog deserves a calm, cozy old age filled with love and care. A private house would be best. For apartments, a first floor or elevator is preferable (otherwise, she must be carried). She holds her potty walks well. We guarantee lifelong medical support if needed. She has a mammary gland tumor, but we decided not to operate — the surgery and recovery would be too hard for her.',
    shelter: 'OOZJ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/8127',
    contactPhone: '+375 (25) 785-07-23, Nastya',
  },
  {
    id: 14,
    name: 'Steve',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/65803379.webp',
    type: 'cat',
    breed: 'Mixed breed',
    age: '2 years',
    color: 'White, short-haired',
    character: 'Smart, independent, balanced',
    toilet: 'Litter box trained with filler',
    medicalNeeds:
      'Fully treated for skin parasites. Neutered. Vaccinated on 26.07.2025 - Nobivac Tricat + Rabies',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-08-14',
    history:
      'Steve is an adult cat with a well-formed personality: calm, self-sufficient, moderately sociable, yet always eager for human attention. He greets people happily, starts purring right away, and you can see how much he wants to be close to his person. This handsome snow-white gentleman was found on the street already neutered and is about 5 years old. His ears are slightly deformed from street life, but his hearing is fine and no special care is required. Steve used to live in a home, as he knows all the rules of apartment life and doesn’t need to be taught anything. During his time in foster care, we’ve learned he’s also very intelligent — neat, moderately active, calm, not prone to conflict, though not very social with other cats.',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/30-1-0-8407',
    contactPhone: '+375 (29) 151-90-80, Natalia',
  },
  {
    id: 15,
    name: 'Caramelkin',
    gender: 'Male',
    photo: 'https://egida.by/_dr/83/75351104.webp',
    type: 'kitten',
    breed: 'Mixed breed',
    age: '3 months',
    color: 'White, ginger, short-haired',
    character: 'Shy, gentle, friendly with other cats',
    toilet: 'Litter box trained with filler',
    medicalNeeds:
      'Fully treated for skin parasites. Vaccinated on 30.05.2025 - Nobivac Tricat Trio',
    feeding: 'High-quality mixed feeding',
    foundAt: '2025-06-21',
    history:
      'A very beautiful and modest little boy, Caramelkin, is looking for a loving family. About 3.5 months old, vaccinated, and litter box trained. He’s a bit cautious around people at first, but once you hold him, his tender and affectionate soul immediately shows — he starts purring and relaxing in your arms. Caramelkin is especially kind and friendly toward other cats: gentle, affectionate, loves cuddles, and enjoys grooming his feline friends. So if you already have a cat who’s bored when left alone, our peachy boy will make a wonderful companion! If you’d like to give him a place in your home and heart, call or message on Viber (if the curator doesn’t answer).',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/8398',
    contactPhone: '+375 (29) 572-86-15, Olga',
  },
  {
    id: 16,
    name: 'Maya',
    gender: 'Female',
    photo: 'https://egida.by/_dr/84/46287712.webp',
    type: 'cat',
    breed: 'Mixed breed',
    age: '1 year',
    color: 'Tricolor, short-haired',
    character: 'Very affectionate, sociable, tidy',
    toilet: 'Litter box trained with filler',
    medicalNeeds:
      'Fully treated for skin parasites. Spayed. Vaccinated on 22.06.2025 - Nobivac Tricat Trio',
    feeding: 'Mixed feeding',
    foundAt: '2025-08-02',
    history:
      'Maya is a young (about 1 year old), affectionate, clean, and very beautiful cat! She is very people-oriented and adores attention. Unfortunately, she has been diagnosed with FIV (Feline Immunodeficiency Virus) — a condition that has become increasingly common. It’s completely safe for humans and other animals but can be risky for healthy cats. This means that Maya must live alone in the shelter, in a separate cage. At the moment, the disease shows no symptoms and requires no treatment or special care. If you like Maya, contact the curator — she will gladly answer all your questions and introduce you to this lovely girl!',
    shelter: 'House of Saved Souls (HSS)',
    linkToPlatform: 'https://egida.by/catalog/30-1-0-8402',
    contactPhone: '+375 (29) 195-95-44, Veronika',
  },
  {
    id: 17,
    name: 'Halvichkin',
    gender: 'Male',
    photo: 'https://egida.by/_dr/84/83020400.webp',
    type: 'kitten',
    breed: 'Mixed breed',
    age: '6 months',
    color: 'Gray, short-haired',
    character: 'Playful, independent, friendly with other cats',
    toilet: 'Litter box trained with filler',
    medicalNeeds:
      'Fully treated for skin parasites. Neutered. Vaccinated on 20.06.2025 - Nobivac Tricat Trio + Rabies',
    feeding: 'High-quality mixed feeding',
    foundAt: '2025-07-19',
    history:
      'Charming Halvichkin is waiting for his loving people! A charismatic boy with stunning coffee-colored eyes and adorable striped legs will not only decorate your home but also fill it with warmth and coziness. Halvichkin is a cheerful and playful guy who will never let you get bored — his acrobatic games can make anyone smile! He’s also kind and friendly with other cats, so if you’re looking for a companion for your pet, he’s a perfect match! Healthy, vaccinated, and litter-trained (even uses a covered box). If you’re looking for a whiskered friend to love, play with, and spoil with treats — call or text on Viber. Halvichkin is eagerly waiting to meet you!',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/8400',
    contactPhone: '+375 (29) 572-86-15, Olga',
  },
  {
    id: 18,
    name: 'Vanilka',
    gender: 'Female',
    photo: 'https://egida.by/_dr/83/02661029.webp',
    type: 'cat',
    breed: 'Mixed breed',
    age: '3 years',
    color: 'Tricolor, short-haired',
    character: 'Playful, affectionate, curious',
    toilet: 'Litter box trained with filler',
    medicalNeeds: 'Fully treated for skin parasites. Spayed.',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-06-03',
    history:
      'Vanilka was rescued from an apartment building where she was abandoned — scared and confused. Now she is a gentle and loving cat who enjoys affection and tenderness. Initially shy and cautious, she soon opens up. Spayed and vaccinated. Vanilka has a unique trait — she snores a bit, likely a result of a past respiratory infection. She’s friendly with other cats, enjoys lounging nearby, and loves tall scratching posts. She adores toys, chasing balls, and having fun. Vanilka is waiting for her new family — one that will truly love her and never betray her again.',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/8394',
    contactPhone: '+375 (44) 730-57-79, Aliona',
  },
  {
    id: 19,
    name: 'Nyusha',
    gender: 'Female',
    photo: 'https://egida.by/_dr/83/12243609.webp',
    type: 'kitten',
    breed: 'Mixed breed',
    age: '8 months',
    color: 'Tricolor, short-haired',
    character: 'Calm, affectionate',
    toilet: 'Litter box trained with filler',
    medicalNeeds: 'Fully treated for skin parasites. Spayed.',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-06-01',
    history:
      'Nyusha is a very shy and timid little girl. At first, she’s cautious and needs time to adjust to a new home and person. Likely, she was mistreated in the past, so patience is required to help her open up and show her love. She’s gentle, enjoys sitting on laps, and playfully nibbles fingers. Calm with other cats, friendly, loves wand toys. Adoption by agreement to responsible hands with follow-up on her well-being.',
    shelter: 'Foster care',
    linkToPlatform: 'https://egida.by/catalog/8392',
    contactPhone: '+375 (29) 325-90-26, Natalia',
  },
  {
    id: 20,
    name: 'Grisha',
    gender: 'Boy',
    photo: 'https://egida.by/_dr/83/78486261.webp',
    type: 'cat',
    breed: 'Mixed breed',
    age: '1 year',
    color: 'Red, Short hair',
    character: 'Playful, affectionate, curious',
    toilet: 'Litter box trained',
    medicalNeeds: 'Fully treated for skin parasites. Neutered.',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-05-29',
    history:
      'Grisha is a very affectionate and sociable cat. Rescued from the street, about one year old. Quickly bonds with new people and gets along with other cats. By nature, Grisha is very brave, loves to be the leader, explore everything, check every corner, and find secret resting spots. He plays with toys, loves fishing-rod toys, mice, and balls. A very kind, charming, and contact-loving cat who will purr, show his belly, and snuggle in your arms at the first opportunity. He will be your best friend and companion. Given under an adoption agreement with gentle follow-up.',
    shelter: 'Home foster care',
    linkToPlatform: 'https://egida.by/catalog/8389',
    contactPhone: '+375 (44) 730-57-79, Alyona',
  },
  {
    id: 21,
    name: 'Myshka',
    gender: 'Girl',
    photo: 'https://egida.by/_dr/84/36029529.webp',
    type: 'kitten',
    breed: 'Mixed breed',
    age: '2 months',
    color: 'Gray, Black and white, Fluffy',
    character: 'Affectionate, sociable, playful',
    toilet: 'Litter box trained',
    medicalNeeds: 'Fully treated for skin parasites.',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2025-10-06',
    history:
      'This little Mouse is not even 2 months old, but she is very smart — already knows how to use the litter box and scratching post, and is playful yet well-behaved. Treated for parasites, eats dry food and kitten pâté. She has recovered from an infection; as a result, she has a small adhesion on the lower eyelid of her right eye, which can be surgically corrected in a few months. Her vision is excellent. Very affectionate, playful, social, and of course, hilariously funny during her kitten games. Gets along with everyone, especially with dogs. Future adopters will receive help with her eyelid surgery.',
    shelter: 'OOZHZ “Egida”',
    linkToPlatform: 'ООЗЖ «Эгида»',
    contactPhone: '+375 (44) 768-26-13, Olga',
  },
  {
    id: 22,
    name: 'Belochka',
    gender: 'Girl',
    photo: 'https://egida.by/_dr/83/10468184.webp',
    type: 'puppy',
    breed: 'Mixed breed',
    age: '8 months',
    color: 'White, Short hair, 45 cm at the withers',
    character: 'Playful, affectionate, curious',
    toilet: 'Learning to walk outside, sometimes uses a pad at home',
    medicalNeeds:
      'Fully treated for skin parasites. Vaccinated on 18.12.2024 — Nobivac DHPPi + L + R',
    feeding: 'Dry food, canned food, preserves',
    foundAt: '2024-05-12',
    history:
      'Belochka is a beauty, slender, sweet as marshmallow, soft and cuddly, cheerful and gentle. Very social, smart, affectionate. Moderately active — enjoys running with other dogs outside, calm at home, prefers to stay close. Not afraid of strangers, adores her people. About 8 months old, healthy, parasite-free, vaccinated, microchipped. Eats both dry and wet food. Learning to walk outdoors, can hold up to 8 hours, but still sometimes uses a pad. Looking for a family as a full member, by adoption agreement, for apartment or house living. Not for kennel or chain.',
    shelter: 'OOZHZ “Egida”',
    linkToPlatform: 'https://egida.by/catalog/8329',
    contactPhone: '+375 (44) 768-26-13, Olga',
  },
  {
    id: 23,
    name: 'Snezinka',
    photo: '/snezhinka.png',
    type: 'cat',
    breed: 'Mixed breed',
    age: '1 year',
    color: 'White',
    character: 'Affectionate, sociable',
    toilet: 'Needs help with toilet',
    feeding: 'Dry food, canned food, preserves',
    history: 'Snezinka was found on the street with paralyzed hind legs.',
    shelter: 'SuperCat',
    linkToPlatform: 'https://superkot.by/catalog/snowflake/',
  },
  {
    id: 24,
    name: 'Johnny',
    photo: '/jony.png',
    type: 'cat',
    breed: 'Mixed breed',
    age: '4 years',
    color: 'Forest color with white chest, smooth coat',
    character: 'Calm and affectionate cat. Loves attention and cuddles.',
    toilet: 'Needs help with toilet, hind legs are paralyzed',
    feeding: 'Dry food, canned food, preserves',
    history: 'Johnny was found on the street with paralyzed hind legs.',
    shelter: 'SuperCat',
    linkToPlatform: 'https://superkot.by/catalog/jonny/',
  },
];
